import i18next from '../../shared/i18n/config';
import { CHILD_PROFILE_LIMIT } from '../../shared/constants/limits';

const t = (key: string, opts?: Record<string, unknown>) => i18next.t(key, { ns: 'dashboard', ...opts });
const arr = <T>(key: string) => i18next.t(key, { ns: 'dashboard', returnObjects: true }) as T;

export const childDetailContent = {
  breadcrumbLabel: t('childDetail.breadcrumbLabel'),
  examReadinessTitle: t('childDetail.examReadinessTitle'),
  examReadinessSubtitle: t('childDetail.examReadinessSubtitle'),
  readinessLabel: t('childDetail.readinessLabel'),
  strongAreasTitle: t('childDetail.strongAreasTitle'),
  strongAreas: arr<string[]>('childDetail.strongAreas'),
  needsAttentionTitle: t('childDetail.needsAttentionTitle'),
  needsAttention: arr<string[]>('childDetail.needsAttention'),
  scoreTrendTitle: t('childDetail.scoreTrendTitle'),
  scoreTrendRange: t('childDetail.scoreTrendRange'),
  scoreTrendPeriod: t('childDetail.scoreTrendPeriod'),
  scoreTrendInsight: t('childDetail.scoreTrendInsight'),
  scoreTrendAttention: t('childDetail.scoreTrendAttention'),
  subjectBreakdownTitle: t('childDetail.subjectBreakdownTitle'),
  learningPathTitle: t('childDetail.learningPathTitle'),
  currentTopicBadge: t('childDetail.currentTopicBadge'),
  passTargetLabel: t('childDetail.passTargetLabel'),
  unlockHintPrefix: t('childDetail.unlockHintPrefix'),
  unlockHintSuffix: t('childDetail.unlockHintSuffix'),
  topicsCompletedOf: t('childDetail.topicsCompletedOf'),
  topicsCompletedSuffix: t('childDetail.topicsCompletedSuffix'),
  weeksRemainingLabel: t('childDetail.weeksRemainingLabel'),
  paceTooltip: t('childDetail.paceTooltip'),
};

export const parentDashboardContent = {
  greetingPrefix: t('parentDashboard.greetingPrefix'),
  greetingSuffix: t('parentDashboard.greetingSuffix'),
  childrenTitle: t('parentDashboard.childrenTitle'),
  recentActivityTitle: t('parentDashboard.recentActivityTitle'),
  addChildTitle: t('parentDashboard.addChildTitle'),
  addChildHelper: t('parentDashboard.addChildHelper', { limit: CHILD_PROFILE_LIMIT }),
  addChildCta: t('parentDashboard.addChildCta'),
  viewActivity: t('parentDashboard.viewActivity'),
  upgradeNow: t('parentDashboard.upgradeNow'),
  resetDiagnosticTitle: t('parentDashboard.resetDiagnosticTitle'),
  needsAttention: t('parentDashboard.needsAttention'),
  noActivityYet: t('parentDashboard.noActivityYet'),
  startDiagnostic: t('parentDashboard.startDiagnostic'),
  startPractice: t('parentDashboard.startPractice'),
  continuePractice: t('parentDashboard.continuePractice'),
  viewDetails: t('parentDashboard.viewDetails'),
  autoSkipLabel: t('parentDashboard.autoSkipLabel'),
  autoSkipDisabledTitle: t('parentDashboard.autoSkipDisabledTitle'),
  resetDiagnostic: t('parentDashboard.resetDiagnostic'),
  neverActivity: t('parentDashboard.neverActivity'),
  testsLabel: t('parentDashboard.testsLabel'),
  diagnosticPending: t('parentDashboard.diagnosticPending'),
  nextTopicPrefix: t('parentDashboard.nextTopicPrefix'),
  topicsSuffix: t('parentDashboard.topicsSuffix'),
  archiveProgressConfirmation: t('parentDashboard.archiveProgressConfirmation'),
  resetDiagnosticDescription: t('parentDashboard.resetDiagnosticDescription'),
  cancel: t('parentDashboard.cancel'),
  editProfile: t('parentDashboard.editProfile'),
  downloadReport: t('parentDashboard.downloadReport'),
  archiveMenuLabel: t('parentDashboard.archiveMenuLabel'),
  streakSuffix: t('parentDashboard.streakSuffix'),
};

export const testHistoryContent = {
  heading: t('testHistory.heading'),
  searchPlaceholder: t('testHistory.searchPlaceholder'),
  sortByDate: t('testHistory.sortByDate'),
  sortByScore: t('testHistory.sortByScore'),
  filterAll: t('testHistory.filterAll'),
  filterMaths: t('testHistory.filterMaths'),
  filterEnglish: t('testHistory.filterEnglish'),
  exportCsv: t('testHistory.exportCsv'),
  exportPdf: t('testHistory.exportPdf'),
  exportPdfTooltip: t('testHistory.exportPdfTooltip'),
  loadMore: t('testHistory.loadMore'),
  colDate: t('testHistory.colDate'),
  colSubject: t('testHistory.colSubject'),
  colTopic: t('testHistory.colTopic'),
  colScore: t('testHistory.colScore'),
  colTime: t('testHistory.colTime'),
};
