import type { School } from "./types";

export const SCHOOL_SELECTION_LIMIT = 4;

export const SCHOOLS: School[] = [
  {
    id: "1",
    name: "Tonbridge Grammar School",
    location: "Tonbridge, Kent",
    gender: "Boys",
    examBoard: "GL Assessment",
    region: "kent",
    popular: true,
  },
  {
    id: "2",
    name: "The Judd School",
    location: "Tonbridge, Kent",
    gender: "Boys",
    examBoard: "GL Assessment",
    region: "kent",
    popular: true,
  },
  {
    id: "3",
    name: "Invicta Grammar School",
    location: "Maidstone, Kent",
    gender: "Girls",
    examBoard: "GL Assessment",
    region: "kent",
    popular: true,
  },
  {
    id: "4",
    name: "Dartford Grammar School",
    location: "Dartford, Kent",
    gender: "Boys",
    examBoard: "GL Assessment",
    region: "kent",
  },
  {
    id: "5",
    name: "Weald of Kent Grammar School",
    location: "Tonbridge, Kent",
    gender: "Girls",
    examBoard: "Kent Test",
    region: "kent",
  },
  {
    id: "6",
    name: "Simon Langton Grammar School for Boys",
    location: "Canterbury, Kent",
    gender: "Boys",
    examBoard: "Kent Test",
    region: "kent",
    popular: true,
  },
  {
    id: "7",
    name: "King Edward's School",
    location: "Birmingham",
    gender: "Boys",
    examBoard: "ISEB",
    region: "birmingham",
  },
  {
    id: "8",
    name: "Withington Girls' School",
    location: "Manchester",
    gender: "Girls",
    examBoard: "CEM",
    region: "other",
  },
  {
    id: "9",
    name: "Reading School",
    location: "Reading, Berkshire",
    gender: "Boys",
    examBoard: "GL Assessment",
    region: "other",
  },
  {
    id: "10",
    name: "Henrietta Barnett School",
    location: "London",
    gender: "Girls",
    examBoard: "GL Assessment",
    region: "other",
    popular: true,
  },
];
